allow to control fluentd replicas from values.yaml
uselagoon/lagoon-charts pull request #244
Opened 2021-03-25 05:11 UTC by tobybellwood

This PR allows helm templates to control the replicas for the fluentd pods inside the logging operator.  It keeps the default at 3, but uses 1 for CI (and we would also use 1 for local development)

2021-03-31 12:35 UTC, smlx approved these changes
LGTM

2021-04-01 05:35 UTC, smlx requested changes

2021-04-01 05:35 UTC, smlx commented on charts/lagoon-logging/ci/linter-values.yaml
> +fluentdreplicaCount: 1
I just realised the capitalisation is not correct here so you'll still get the default `3`.

2021-04-01 06:00 UTC, tobybellwood commented on charts/lagoon-logging/ci/linter-values.yaml
> +fluentdreplicaCount: 1
```suggestion
fluentdReplicaCount: 1
```

2021-04-09 06:02 UTC, merged