Add the ability to change elasticsearch admin username in logs-concentrator
uselagoon/lagoon-charts pull request #328
Opened 2021-09-17 22:20 UTC by KorvinSzanto

This PR makes it possible to configure an elasticsearch username as part of the lagoon-logs-concentrator chart values.yml file.

2021-09-17 22:34 UTC, KorvinSzanto commented
There is still work to do in the lagoon-core chart as well as in https://github.com/uselagoon/lagoon to remove the 'admin' default

2021-09-22 08:44 UTC, smlx requested changes
Needs a very minor change but otherwise looks good!

Also needs a rebase and to bump the minor version number of the `lagoon-logs-concentrator` chart.

2021-09-22 08:44 UTC, smlx commented on charts/lagoon-logs-concentrator/templates/secret.yaml
> +  LOGSDB_ADMIN_USER: {{ default "admin" .Values.elasticsearchAdminUser }}
Minor style thing, but could we change this to have the default value in the `values.yaml`, and just reference `{{ .Values.elasticsearchAdminUser }}` here? This is the style we have used elsewhere in the chart.

2022-04-06 02:43 UTC, smlx commented
@KorvinSzanto just checking if you're still working on this PR?

2022-04-06 04:16 UTC, KorvinSzanto commented
I can take a look tomorrow, thanks for the heads up

2022-04-07 18:50 UTC, KorvinSzanto commented
This should be good  to go, let me know if I missed anything or did anything incorrectly.

2022-04-08 00:51 UTC, merged

2022-04-08 00:51 UTC, smlx commented
Thanks!